# Generated by Django 3.0.2 on 2020-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200808_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='닉네임'),
        ),
    ]
