# Generated by Django 3.0.2 on 2020-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_preference_keward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preference_keward',
            field=models.CharField(blank=True, max_length=255, verbose_name='선호 키워드'),
        ),
    ]
