# Generated by Django 3.0.2 on 2020-09-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200904_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='preference_keward',
            new_name='preference_keyword',
        ),
    ]
