# Generated by Django 3.0.2 on 2020-09-08 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='댓글수')),
                ('community_image', models.ImageField(blank=True, null=True, upload_to='community/%Y/%m/%d', verbose_name='커뮤니티이미지')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('likes', models.ManyToManyField(blank=True, related_name='community_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '커뮤니티',
                'verbose_name_plural': '커뮤니티',
                'db_table': '커뮤니티',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글내용')),
                ('reply', models.IntegerField(default=0, verbose_name='답글위치')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='댓글수정일')),
                ('deleted', models.BooleanField(default=False, verbose_name='댓글삭제여부')),
                ('likes', models.ManyToManyField(blank=True, related_name='community_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='댓글좋아요')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community', verbose_name='게시글')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글작성자')),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글',
                'db_table': '커뮤니티 댓글',
            },
        ),
    ]
