# Generated by Django 3.0.2 on 2020-09-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='community_image',
            new_name='upload_image',
        ),
    ]
