# Generated by Django 3.0.2 on 2020-08-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import menu.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='브랜드')),
                ('title', models.CharField(max_length=64, verbose_name='커스텀메뉴')),
                ('base_menu', models.CharField(max_length=64, verbose_name='원본메뉴')),
                ('ingredient', models.CharField(max_length=64, verbose_name='재료')),
                ('price', models.PositiveIntegerField(default='0', verbose_name='가격')),
                ('tip', models.TextField(verbose_name='팁')),
                ('rating', models.IntegerField(default=0, verbose_name='평점')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments', models.PositiveIntegerField(default='0', verbose_name='댓글수')),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to=menu.models.get_image_path, verbose_name='이미지파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='이미지첨부파일명')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='추천')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='태그')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '커스텀메뉴',
                'verbose_name_plural': '커스텀메뉴',
                'db_table': '커스텀메뉴',
            },
        ),
        migrations.CreateModel(
            name='MenuComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글내용')),
                ('reply', models.IntegerField(default=0, verbose_name='답글위치')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='댓글수정일')),
                ('deleted', models.BooleanField(default=False, verbose_name='댓글삭제여부')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='댓글추천')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='게시글')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글작성자')),
            ],
            options={
                'verbose_name': '커스텀메뉴 댓글',
                'verbose_name_plural': '커스텀메뉴 댓글',
                'db_table': '커스텀메뉴 댓글',
            },
        ),
    ]
