# Generated by Django 3.0.2 on 2020-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='브랜드'),
        ),
    ]
