# Generated by Django 3.0.2 on 2020-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='평점'),
        ),
    ]
