# Generated by Django 3.0.2 on 2020-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200902_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='base_menu',
            field=models.CharField(max_length=255, verbose_name='원본메뉴'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredient',
            field=models.CharField(max_length=255, verbose_name='재료'),
        ),
    ]
