# Generated by Django 3.0.2 on 2020-09-03 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_auto_20200904_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating_user',
            field=models.ManyToManyField(blank=True, related_name='rating_user', to=settings.AUTH_USER_MODEL, verbose_name='별점 등록 사용자'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='별점'),
        ),
    ]
