# Generated by Django 3.0.2 on 2020-09-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200905_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBaseMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='브랜드')),
                ('name', models.CharField(max_length=64, verbose_name='원본메뉴')),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='base_menu/', verbose_name='원본메뉴이미지')),
            ],
            options={
                'verbose_name': '원본메뉴',
                'verbose_name_plural': '원본메뉴',
                'db_table': '원본메뉴',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='base_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='base_menu',
            field=models.ManyToManyField(blank=True, related_name='base_menu', to='menu.MenuBaseMenu', verbose_name='원본메뉴'),
        ),
    ]
