# Generated by Django 3.0.2 on 2020-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200907_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuBaseMenu',
            new_name='BaseMenu',
        ),
    ]
