# Generated by Django 3.0.2 on 2020-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_basemenu_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemenu',
            name='price',
            field=models.IntegerField(default='0', verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='menuingredient',
            name='price',
            field=models.IntegerField(default='0', verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='basemenu',
            name='name',
            field=models.CharField(max_length=64, verbose_name='메뉴이름'),
        ),
    ]
